# pyre-ignore-all-errors
"""
train_classification.py
-----------------------
Trains a RandomForest classifier to predict whether an intern is at-risk.

Definition of at-risk:
    productivity_score < median(productivity_score)  OR  avg_score < 70

Run this once after main.py to generate classification_model.pkl
"""

import os
import sys
import pickle
import json
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (
    accuracy_score, classification_report,
    roc_auc_score
)
from sklearn.preprocessing import StandardScaler

# Add parent dir to path so config is importable
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def train_classification_model(ml_dir, models_dir):
    print("--> Training At-Risk Classification model...")

    # -------------------------------------------------------
    # LOAD ML OUTPUT CSVs (generated by main.py)
    # -------------------------------------------------------
    summary      = pd.read_csv(os.path.join(ml_dir, "intern_summary.csv"))
    clusters     = pd.read_csv(os.path.join(ml_dir, "intern_clusters.csv"))
    productivity = pd.read_csv(os.path.join(ml_dir, "intern_productivity.csv"))
    engagement   = pd.read_csv(os.path.join(ml_dir, "engagement_scores.csv"))

    # Merge all
    df = summary.merge(clusters[['intern_id','category']], on='intern_id')
    df = df.merge(productivity[['intern_id','predicted_productivity']], on='intern_id')
    df = df.merge(engagement[['intern_id','number_of_activities','active_days']], on='intern_id')

    # -------------------------------------------------------
    # CREATE LABEL
    # at_risk = 1 if productivity < median OR avg_score < 70
    # -------------------------------------------------------
    median_prod  = df['productivity_score'].median()
    df['at_risk'] = (
        (df['productivity_score'] < median_prod) |
        (df['avg_score'] < 70)
    ).astype(int)

    print(f"  At-risk distribution: {df['at_risk'].value_counts().to_dict()}")
    print(f"  Productivity median used as threshold: {median_prod:.2f}")

    # -------------------------------------------------------
    # FEATURES & LABEL
    # -------------------------------------------------------
    feature_cols = ['active_days', 'number_of_activities',
                    'tech_count', 'hours_spent', 'avg_score']
    X = df[feature_cols]
    y = df['at_risk']

    # -------------------------------------------------------
    # SCALE
    # -------------------------------------------------------
    scaler  = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # -------------------------------------------------------
    # TRAIN / TEST SPLIT
    # -------------------------------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=42, stratify=y
    )

    # -------------------------------------------------------
    # TRAIN RANDOM FOREST
    # -------------------------------------------------------
    clf = RandomForestClassifier(
        n_estimators=100,
        max_depth=4,
        random_state=42,
        class_weight='balanced'   # handles imbalance
    )
    clf.fit(X_train, y_train)

    # -------------------------------------------------------
    # EVALUATE
    # -------------------------------------------------------
    y_pred  = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(y_test, y_pred)
    roc_auc  = roc_auc_score(y_test, y_proba)
    cv_scores = cross_val_score(clf, X_scaled, y, cv=5, scoring='accuracy')

    metrics = {
        "At_Risk_Classification": {
            "Train_Size"          : int(len(X_train)),
            "Test_Size"           : int(len(X_test)),
            "Accuracy"            : round(float(accuracy), 4),
            "Accuracy_Percentage" : f"{round(accuracy * 100, 2)}%",
            "ROC_AUC"             : round(float(roc_auc), 4),
            "CV_Accuracy_Mean"    : round(float(cv_scores.mean()), 4),
            "CV_Accuracy_Std"     : round(float(cv_scores.std()), 4),
            "Feature_Importance"  : dict(zip(
                feature_cols,
                [round(float(i), 4) for i in clf.feature_importances_]
            ))
        }
    }

    print(f"  Accuracy     : {accuracy:.4f}")
    print(f"  ROC-AUC      : {roc_auc:.4f}")
    print(f"  CV Accuracy  : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
    print(f"\n  Classification Report:\n{classification_report(y_test, y_pred)}")

    # -------------------------------------------------------
    # SAVE MODEL
    # -------------------------------------------------------
    os.makedirs(models_dir, exist_ok=True)
    model_path = os.path.join(models_dir, "classification_model.pkl")
    with open(model_path, 'wb') as f:
        pickle.dump({
            'model'       : clf,
            'scaler'      : scaler,
            'features'    : feature_cols,
            'threshold'   : float(median_prod),
            'label_map'   : {0: 'Not At Risk', 1: 'At Risk'}
        }, f)

    # -------------------------------------------------------
    # APPEND TO model_evaluation.json
    # -------------------------------------------------------
    eval_path = os.path.join(ml_dir, "model_evaluation.json")
    if os.path.exists(eval_path):
        with open(eval_path) as f:
            existing = json.load(f)
        existing.update(metrics)
        with open(eval_path, 'w') as f:
            json.dump(existing, f, indent=4)
    else:
        with open(eval_path, 'w') as f:
            json.dump(metrics, f, indent=4)

    print(f"  Saved → {model_path}")
    print(f"  Updated → {eval_path}")
    return model_path, metrics


# -------------------------------------------------------
# STANDALONE RUN
# -------------------------------------------------------
if __name__ == "__main__":
    base_dir   = r"e:\Intern Analysys"        # change to your path
    ml_dir     = os.path.join(base_dir, "ml")
    models_dir = os.path.join(base_dir, "models")
    train_classification_model(ml_dir, models_dir)
